// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fohoticyvvddiqvdvjuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvaG90aWN5dnZkZGlxdmR2anVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MzM2MTMsImV4cCI6MjA1NjQwOTYxM30.9G9TEOJcI1PXhOGkRjRIduZ9df_ekn8IinfpvZJUfy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);